[package]
name = "simplex_web"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.103"
web-sys = { version = "0.3.80", features = ["console"] }
yew = { version = "0.21.0", features = ["csr"] }
